#!/bin/bash

# remove inline LaTeX
sed -i'' -e "s/\\\pagebreak//g" ${PWD}/tmp/VeRsIoN.md

# Use the version file generated by Makefile
PRODUCT_VERSION=`cat ../../../hpc-shs-version/shs-version`
echo "VERSION PASSED TO DITA BUILD IS $PRODUCT_VERSION"
DOCS_GIT_HASH=`grep -C 1 "Doc git hash" ${PWD}/tmp/VeRsIoN.md | tail -n 1`
echo "GIT HASH PASSED TO DITA BUILD IS $DOCS_GIT_HASH"
for file in $(find ./tmp -name "*.json");do	
	sed -i'' -e "s/@product_version@/$PRODUCT_VERSION/g" $file
	sed -i'' -e "s/@docs_git_hash@/$DOCS_GIT_HASH/g" $file 
	done
for file in $(find ./tmp -name "*.ditamap");do	
	sed -i'' -e "s/@product_version@/$PRODUCT_VERSION/g" $file
	sed -i'' -e "s/@docs_git_hash@/$DOCS_GIT_HASH/g" $file
	done

# replace variables in the XML header files used for the single file HTML5 output
for file in $(find ./tmp -name "*.xml");do
	sed -i'' -e "s/@product_version@/$PRODUCT_VERSION/g" $file
	sed -i'' -e "s/@docs_git_hash@/$DOCS_GIT_HASH/g" $file 
	done
