name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 1 * * *'

jobs:
  create-runner:
    name: Create Runner
    uses: hpc-sw/create_runners/.github/workflows/create_runners.yaml@master
    secrets: inherit

  stale:
    needs: create-runner
    runs-on: ['${{ needs.create-runner.outputs.runner_name }}', 'ignore']
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'