# This is a basic workflow to help you get started with Actions

name: RunnerActionTest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-runner:
    name: Create Runner
    uses: hpc-sw/create_runners/.github/workflows/create_runners.yaml@master
    secrets: inherit

  build:
    needs: create-runner
    runs-on: ['${{ needs.create-runner.outputs.runner_name }}', 'ignore']
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          echo Hello, world!!!!!
          python --version
